version: '3.7'
services:
  svc-bills:
    image: wortiz1027/svc-bills:latest
    container_name: svc-bills
    hostname: svc-bills
    restart: always
    ports:
      - 8081
      - 6181
    environment:
      - SERVER_CONFIG=http://server-config:7070
      - SERVER_DISCOVERY=http://server-discovery:7071/eureka
      - SERVER_DISCOVERY_HOST=server-discovery
      - SERVER_BROKER_HOST=server-broker
    networks:
      - ntw_backend
  svc-clients:
    image: wortiz1027/svc-clients:latest
    container_name: svc-clients
    hostname: svc-clients
    restart: always
    ports:
      - 8082
      - 6182
    environment:
      - SERVER_CONFIG=http://server-config:7070
      - SERVER_DISCOVERY=http://server-discovery:7071/eureka
      - SERVER_DISCOVERY_HOST=server-discovery
      - SERVER_BROKER_HOST=server-broker
    networks:
      - ntw_backend
  svc-products:
    image: wortiz1027/svc-products:latest
    container_name: svc-products
    hostname: svc-products
    restart: always
    ports:
      - 8083
      - 6183
    environment:
      - SERVER_CONFIG=http://server-config:7070
      - SERVER_DISCOVERY=http://server-discovery:7071/eureka
      - SERVER_DISCOVERY_HOST=server-discovery
      - SERVER_BROKER_HOST=server-broker
    networks:
      - ntw_backend
networks:
  ntw_backend:
    external: true
